version: "3.9"
services:
  db:
    image: postgres
    restart: always
    # env_file: .env.pq
    environment:
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_USER=jianrong
      - POSTGRES_DB=cvwo
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  server:
    build: .
    env_file: .env
    depends_on:
      - db
    links:
      - db
    networks:
      - default
    ports:
      - "3000:3000"
volumes:
  db: